# Use root/example as user/password credentials
version: '3.8'

networks:
  dbCompare:

services:
  vue-frontend:
    container_name: vue-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    container_name: vue-frontend
    networks: 
      - dbCompare
    volumes:
      - './frontend:/app'
      - '/app/node_modules'

  django-api:
    container_name: django
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/
    environment:
      SERVICE_PRECONDITION: "clickhouse-server:9000"
    networks: 
      - dbCompare
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - ./.env.dev

  clickhouse-server:
    container_name: clickhouse
    image: yandex/clickhouse-server
    restart: always
    networks: 
      - dbCompare
    # command: service clickhouse-server start
    ports:
      - "2020:22"
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks: 
      - dbCompare
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    networks: 
      - dbCompare
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root